name: gym-duckietown
channels:
    - pytorch
    - defaults
dependencies:
    - python=3.11
    - pytorch=2.3
    - torchvision
    - pyzmq
    - numpy
    - pyyaml=6.0.1
    - pip
    - pip:
        - gym
        - pyglet
        - opencv-python
        - scikit-image
